# Configurare InfiniteSculk

# Activeaza sau dezactiveaza complet functionalitatea pluginului
enabled: true

# Daca este true, ignora XP-ul real lasat de mob si foloseste direct charge-power
bypass-xp-requirement: true

# Multiplicator de viteza folosit cand bypass-xp-requirement este false
spread-speed-multiplier: 2

# Puterea de incarcare (charge) injectata cand bypass-xp-requirement este true
charge-power: 1000
